version: '3.8'

services:
  web:
    build: .
    container_name: tutorialzend_web
    ports:
      - "8080:80"
    volumes:
      # Em desenvolvimento, montamos o código como volume
      - .:/var/www/html
      # Persiste os uploads mesmo se o container for recriado
      - uploads:/var/www/html/public/uploads
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db
    networks:
      - tutorialzend_network

  db:
    image: mysql:8.0
    container_name: tutorialzend_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tutorialzend
      MYSQL_USER: tutorialzend_user
      MYSQL_PASSWORD: tutorialzend_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - tutorialzend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tutorialzend_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    depends_on:
      - db
    networks:
      - tutorialzend_network

volumes:
  db_data:
  uploads:

networks:
  tutorialzend_network:
    driver: bridge